version: "3"

services:
  next-app:
    container_name: next14-docker
    build:
      context: .
      dockerfile: Dockerfile

   
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
   